language: rust

env:
  global:
    - secure: jDWiPLNAaU65HiFsS1YiWi+XOpL/1inE5VDmSILdXBSFe5x+vIgdPJiWMQuN1VcBOiJAnTz0FkYogvkQmvTeZ7aJlAih7LokpHNFszIWBEQW2qWDy5XvBec/DUCRT0iVeOmgu34jjuai1qBgSUkUFRFaKoKSdWVAruTW5S2EiRs=

script:
- cargo build --verbose
- cargo test --verbose
- cargo doc --verbose

after_script:
  - ln -s target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
