[package]

name = "ssap"
version = "0.0.1"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "AGPL-3.0"
keywords = ["parse", "arguments"]
description = "A simple structured argument parser"
repository = "https://github.com/jmesmon/rust-ssap"
